<a href="https://colab.research.google.com/github/biplabp455/Skill-Morph-ML-Training/blob/main/SkillMorph_4_NumPy_and_Pandas_for_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy and Pandas for Machine Learning**

**Instructor:** Md. Samiul Islam - Skill Morph Research Lab

**Date:** Dec 30, 2025, 8:00 PM

---

# 1. Introduction to NumPy and Pandas
This section introduces the basics of NumPy and Pandas for Machine Learning.

## 1.1 NumPy Basics
Learn how to create arrays and perform basic array operations.


In [ ]:
# Install required packages
!pip install numpy pandas matplotlib

# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
import warnings
warnings.filterwarnings('ignore')

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 2.0.2
Pandas version: 2.2.2


In [ ]:
# Creating NumPy arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)
print("Array shape:", arr2.shape)
print("Array dtype:", arr1.dtype)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Array shape: (2, 3)
Array dtype: int64


## 1.2 Creating NumPy Arrays


In [ ]:
# Different ways to create arrays
zeros_array = np.zeros((3, 4))
ones_array = np.ones((2, 3))
range_array = np.arange(0, 10, 2)
linspace_array = np.linspace(0, 1, 5)

print("Zeros array:\n", zeros_array)
print("Ones array:\n", ones_array)
print("Range array:", range_array)
print("Linspace array:", linspace_array)

Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


## 1.3 Different Ways to Create Arrays


In [ ]:
# Mathematical operations on arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 3, 4, 5, 6])

# Element-wise operations
print("Addition:", a + b)
print("Multiplication:", a * b)
print("Power:", a ** 2)
print("Square root:", np.sqrt(a))

# Statistical operations
print("Mean:", np.mean(a))
print("Standard deviation:", np.std(a))
print("Min:", np.min(a))
print("Max:", np.max(a))

# Broadcasting example
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])
result = matrix + vector
print("Broadcasting result:\n", result)

Addition: [ 3  5  7  9 11]
Multiplication: [ 2  6 12 20 30]
Power: [ 1  4  9 16 25]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Mean: 3.0
Standard deviation: 1.4142135623730951
Min: 1
Max: 5
Broadcasting result:
 [[11 22 33]
 [14 25 36]]


## 1.4 Mathematical Operations on Arrays


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Indexing
print("Element at index 2:", arr[2])

# Slicing
print("Sliced array (from index 1 to 3):", arr[1:4])

# 2D array slicing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Sliced 2D array (first two rows):\n", arr_2d[:2])

Element at index 2: 30
Sliced array (from index 1 to 3): [20 30 40]
Sliced 2D array (first two rows):
 [[1 2 3]
 [4 5 6]]


## 1.5 Array Indexing and Slicing


In [ ]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [24, 27, 22],
        'City': ['New York', 'Los Angeles', 'Chicago']}

df = pd.DataFrame(data)
print("DataFrame:\n", df)

DataFrame:
       Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago


# 2. Introduction to Pandas

## 2.1 Creating DataFrames


In [ ]:
# Basic DataFrame information
print("\nDataFrame Info:")
print(df.info())
print("\nDataFrame Description:")
print(df.describe())
print("\nDataFrame Shape:", df.shape)
print("Column names:", df.columns.tolist())
# Display first 5 rows
print("First 5 rows of the dataset:")
print(df.head())
# Display last 5 rows
print("\nLast 5 rows of the dataset:")
print(df.tail())
# Check data types
print("\nData Types:")
print(df.dtypes)


DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None

DataFrame Description:
             Age
count   3.000000
mean   24.333333
std     2.516611
min    22.000000
25%    23.000000
50%    24.000000
75%    25.500000
max    27.000000

DataFrame Shape: (3, 3)
Column names: ['Name', 'Age', 'City']
First 5 rows of the dataset:
      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

Last 5 rows of the dataset:
      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

Data Types:
Name    object
Age      int64
City    object
dtype: object


## 2.2 DataFrame Information and Description


In [ ]:
# Accessing a single column
print("Names column:\n", df['Name'])

# Accessing multiple columns
print("\nName and Age columns:\n", df[['Name', 'Age']])


Names column:
 0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

Name and Age columns:
       Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22


## 2.3 Converting NumPy Array to DataFrame


In [ ]:
# Convert NumPy array to DataFrame
np_array = np.random.randn(5, 3)
df_from_array = pd.DataFrame(np_array, columns=['A', 'B', 'C'])
print("DataFrame from NumPy array:")
print(df_from_array)

DataFrame from NumPy array:
          A         B         C
0 -0.085172  0.029033 -1.201793
1 -0.611673  0.900815  0.202924
2  1.289272  1.383348 -0.355916
3 -0.083955  0.060473 -0.453566
4 -0.532790  1.958564  0.136441


# 3. Loading Datasets

## 3.1 Loading from Google Drive


In [ ]:
drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/datasets/diabetes.csv'

df = pd.read_csv(file_path)
print("Dataset loaded successfully. Shape:", df.shape)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Dataset loaded successfully. Shape: (768, 9)


## 3.2 Uploading Files to Colab


In [ ]:
from google.colab import files
uploaded = files.upload()

# Load the uploaded file
import io
df = pd.read_csv(io.BytesIO(uploaded['diabetesversion1.csv']))

## 3.3 Converting DataFrame to NumPy Array


In [ ]:
data_array = df.values
print("NumPy array shape:", data_array.shape)
print("Data type:", data_array.dtype)


NumPy array shape: (768, 9)
Data type: float64


# 4. Data Exploration

## 4.1 Quick Overview


In [ ]:
# Quick overview
print(df.head())
print("\nDataset info:")
print(df.info())

# Basic statistics
print("\nDescriptive statistics:")
print(df.describe())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose       

## 4.2 Checking Missing Values


In [ ]:
#missing values
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64


# 5. Practice Exercises

## 5.1 NumPy Exercise


In [ ]:
# Import necessary library
import numpy as np

# Create a NumPy array with 20 random integers between 1 and 100


# Display the NumPy array


# 1. Find the sum of all elements



# 2. Find the maximum and minimum values in the array

## 5.2 Pandas Exercise


In [ ]:
# Import necessary libraries
import pandas as pd
import numpy as np

# 1. Create a DataFrame with 5 rows and 3 columns of random numbers
# The DataFrame is generated from a 5x3 matrix of random integers between 1 and 100.


# Display the DataFrame


# 2. Compute the sum of each column
# The .sum() function computes the sum for each column in the DataFrame.


# 3. Compute the mean of each column
# The .mean() function computes the mean (average) of each column in the DataFrame.


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
import warnings
print("Numpy Version: ", np.__version__)
print("Pandas Version: ", pd.__version__)

Numpy Version:  2.0.2
Pandas Version:  2.2.2


In [9]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3], [4,5,6]])
print("1d array:", arr1)
print("2d array:", arr2)
print("array shape", arr1.shape)
print("array type: ", arr2.dtype)

1d array: [1 2 3 4 5]
2d array: [[1 2 3]
 [4 5 6]]
array shape (5,)
array type:  int64


In [18]:
#Different ways to create array

zeros_array = np.zeros((3,4),dtype=int)
ones_array = np.ones((2,3), dtype=int)
range_array = np.arange(0,10,2)
linspace_array = np.linspace(0,1,5)
print("Zeros array:\n", zeros_array)
print("Ones_array:\n", ones_array)
print("range_array:\n", range_array)
print("linspace_array:\n", linspace_array)
print("Zeros_array Type: ", zeros_array.dtype)
print("Ones_Array Type:", ones_array.dtype)

Zeros array:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Ones_array:
 [[1 1 1]
 [1 1 1]]
range_array:
 [0 2 4 6 8]
linspace_array:
 [0.   0.25 0.5  0.75 1.  ]
Zeros_array Type:  int64
Ones_Array Type: int64


In [21]:
#Elementwise operation

a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,6])
print("Addition: ", a+b)
print("Multiplication: ", a*b)
print("Power: ", a**2)
print("Square Root: ", np.sqrt(b))


Addition:  [ 3  5  7  9 11]
Multiplication:  [ 2  6 12 20 30]
Power:  [ 1  4  9 16 25]
Square Root:  [1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [31]:
#Statistical Operation

a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,6])
print("Mean of A: ", np.mean(a))
print(f"Standard Deviation of A {np.std(a):.3f}")
print("Min of A", np.min(a))
print("Max of A", np.max(a))
print("Max of B", np.max(b))
print("Min of B", np.min(b))


Mean of A:  3.0
Standard Deviation of A 1.414
Min of A 1
Max of A 5
Max of B 6
Min of B 2


In [32]:
#Broadcasting Example

matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([10,20,30])
Result = matrix + vector
print(Result)

[[11 22 33]
 [14 25 36]]


In [43]:
#Mathematical Operation in array
arr = np.array([10,20,30,40,50])
print("Element at index 2: ", arr[2])

arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr_2d)
print("Sliced 2D array (from index 1 to 3):", arr_2d[:2])

Element at index 2:  30
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sliced 2D array (from index 1 to 3): [[1 2 3]
 [4 5 6]]


In [60]:
#Creating Dataframes

data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age' : [24, 27, 22],
        'City' : ['New York', 'Los Angeles', 'Chicago']
        }
df = pd.DataFrame(data)
#print("DataFrame:\n", df)
print(df.info())
print(df.describe())
print(df.shape)
print(df.dtypes)
print("First 2 rows", df.head(2))
print("Last 2 rows", df.tail(2))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None
             Age
count   3.000000
mean   24.333333
std     2.516611
min    22.000000
25%    23.000000
50%    24.000000
75%    25.500000
max    27.000000
(3, 3)
Name    object
Age      int64
City    object
dtype: object
First 2 rows     Name  Age         City
0  Alice   24     New York
1    Bob   27  Los Angeles
Last 2 rows       Name  Age         City
1      Bob   27  Los Angeles
2  Charlie   22      Chicago


In [63]:
#Converting NumPy Array to DataFrame

np_array = np.random.randn(5, 3)
df_from_array = pd.DataFrame(np_array, columns = ['A', 'B', 'C'])
print(df_from_array)

          A         B         C
0 -0.581824  0.288467 -0.365121
1  0.161183  0.303104  0.167605
2 -1.734337  0.375206 -0.776379
3 -0.251871  0.075410  0.688107
4 -0.572115  0.750001  1.119554


In [74]:
#Loading Dataset from drive
from google.colab import drive
import warnings
warnings.filterwarnings('ignore')
drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/Dataset/diabetes.csv'
df = pd.read_csv(file_path)
print("Dataset loaded successcully. Shape:", df.shape)





Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Dataset loaded successcully. Shape: (768, 9)


In [77]:
#Uploading dataset from local drive

from google.colab import files
uploaded = files.upload()
import io
import pandas as pd
df = pd.read_csv(io.BytesIO(uploaded[diabetes(1).csv]))
print(df.head())

Saving diabetes(1).csv to diabetes(1).csv


NameError: name 'diabetes' is not defined

In [79]:
from google.colab import files
uploaded = files.upload()

# Print the uploaded file names to check the exact name
print(uploaded.keys())

import io
import pandas as pd

# Replace the key with the correct name based on what is printed
df = pd.read_csv(io.BytesIO(uploaded[diabetes.csv]))  # Use the correct name from the print statement

print(df.head())

Saving diabetes.csv to diabetes (7).csv
dict_keys(['diabetes (7).csv'])


NameError: name 'diabetes' is not defined

In [83]:
#Loading Dataset from drive
from google.colab import drive
import warnings
warnings.filterwarnings('ignore')
drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/Dataset/diabetes.csv'
df = pd.read_csv(file_path)
print("Dataset loaded successcully. Shape:", df.shape)
print(df.head(15))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Dataset loaded successcully. Shape: (768, 9)
    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0             6      148             72             35        0  33.6   
1             1       85             66             29        0  26.6   
2             8      183             64              0        0  23.3   
3             1       89             66             23       94  28.1   
4             0      137             40             35      168  43.1   
5             5      116             74              0        0  25.6   
6             3       78             50             32       88  31.0   
7            10      115              0              0        0  35.3   
8             2      197             70             45      543  30.5   
9             8      125             96              0        0   0.0   
10            4      11